### PR TITLE
Dimension annotation

### PR DESCRIPTION
**Pull request by akofke**
Split dimensions into separate subpackage. Add dimensioned annotation for future use with introspection.

### CODE REVIEW

**Comment by akofke** [comment]
@ajschult I had to do some decent merge conflict resolution on stuff like interfacialSWGraphic when rebasing this on master, it should be fine but maybe you should take a look.

**Comment by ajschult** [comment]
Hmm, but look at what? I can't see the conflict resolution changes you made...

**Comment by akofke** [comment]
I guess just check if they're still sane (compared to master). But it looks like the only net changes were changing the package paths for dimensions.

**Review by ajschult — APPROVED** [review]
just seems to be whitespace and import changes

**Pull request merged**
